name: Execute Python Script To Convert Vehicles to WEB

# Choose when you want the script to run
on:
  push:
    branches: [ "main" ]  # Runs automatically when you push to the main branch
    paths:
      - 'data/vehicles/raw/**'
  workflow_dispatch:      # Allows you to click a button and run it manually

permissions:
  contents: write

jobs:
  convert-vehicles:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code into the runner
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up a secure Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your preferred version

      # Step 3: Install optional packages (uncomment if you have a requirements.txt)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Step 4: Execute the Python file
      - name: Convert Vehicles for WEB application
        run: python data/vehicles/convert-to-web.py data/vehicles/raw data/vehicles/web

      # Step 5: Commit and push the generated files
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

          # ПРИМУСОВО додаємо файли, ігноруючи .gitignore
          git add -f data/vehicles/web/

          # Перевірка, чи з'явилися файли в індексі Git
          if [ -z "$(git status --porcelain)" ]; then
            echo "Working tree is clean. Nothing to commit."
          else
            git commit -m "Automated file update from GitHub Actions"
            git push
          fi
